language: python
dist: xenial
python:
- '3.5'
- '3.6'
- '3.7'
- '3.8'
- nightly

deploy:
  provider: pypi
  username: __token__
  password:
    secure: DYSRZoQNv5am90LXlLV0ZThoFCznT/wrX+8ex+6ANb+BJQlWL2G1F8u+XGBPlsvMiFXIZzmwR5C+2pWEhvli58gzMGsQXTY9olgcGabwlCIyAJdtEJPdjtsZsA+Kq5sIiBIDClpoeovNHhjeJaNExqqFaC+yYiQ+VL1p5GfknoemXmzTs78pXnodLLCM0k+jN/05mB5qd7RSjHWK5nvxBcJBcVfVHOe1aFvHnGNu2USj47RyyQxFVlxjTPfdZWXLFQejWJBkSVwQBiuJ/9Pk1wdbmU1cNYvX9p20jRSEtuw2iTeGjEbOm7PcCAw9LZxHRL5jddZnWfJj4mr8EFl+Qr80XIHCziwjNoZPlZBfsce6d2v/o6mMzko+WjkUOZnJCi2NsgT0diWMfHluXJhzDnqsZgwSVN+kIq4vpNpj1rPTCx2Q+VWd82VhuzyvB9PenKqCbPffZDNrISCbs3NrnqB4mCgkY4Z4/1w3FDcYaQlfRSoTRYzQ4edB5u590ZgfpFIdQLJLImvatdd7vjG74bTzR+IPA3GwqcPJ11gFgPyqSzX4MxpkQ+kPa57LB+MfM2tF7gKejqVlGuP7iguiseVztcC9kH2+YbiTuU0WHqlmBc+sNmNlYF01966XVNrk8XBytc2gsZuIJRdjwioP4NMK9grewdQIH8wPj3PDB9Q=
  on:
    tags: true
  skip_existing: true
  distributions: "sdist bdist_wheel"

before_install:
- pip install -U pip
- export PYTHONPATH=$PYTHONPATH:$(pwd)

install:
- pip install tox

script:
- tox -v -e py
